# *** LIST OF ACCOUNTS  **********************************************************

# Starting Admin (User #1): 
# { "email": "jed@jed.com", "password": "MagicPassword1234!"}

# Admin (User #):
# { "email": "jed@jed.com", "password": "MagicPassword1234!"}

# Staff (User #2):
# {"email": "clear@dave.com", "password": "CleanTables1234!"}

# Staff (User #8):
# {"email": "boy@dave.com", "password": "CleanFloors!"}

# Employee (User #3):
# {"email": "johndoe@company.com", "password": "I Love Burgers!"}
###
@email = "jed@jed.com"
@password = "MagicPassword1234!"
@authToken = {{login.response.headers.X-AuthToken}}
@CSRFToken = It40wr8sS0X6XNUhHIk9zNOIMxVr85w48xyjcrqJ14r7Dbh4KsQ8mkQU7rRMp8RU
@baseURL = http://127.0.0.1:8000/

###





# *** LOGIN and LOGOUT **********************************************************
POST {{baseURL}}login/ 
Content-Type: application/json

{"email": {{email}}, "password": {{password}}}

###

POST {{baseURL}}logout/ 
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###





# *** CRUD capabilities for Tenant **********************************************
GET {{baseURL}}tenants/ 
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###

POST {{baseURL}}tenant/new/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{ "name": "boom.com" }

###

PUT {{baseURL}}tenant/5/ 
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{"name": "bob.com"}

###

DELETE {{baseURL}}tenant/delete/5/ 
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###





# *** CRUD capabilities for User ***********************************************
GET {{baseURL}}users/ 
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###

POST {{baseURL}}users/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{"name": "HR Jennifer", "email": "jennifer@hr.com", "password": "MyNameIsJennifer1234!"}

###

PUT {{baseURL}}user/9/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{"is_staff": true }

###

DELETE  {{baseURL}}user/6/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###






# *** CRUD capabilities for Project *********************************************
GET {{baseURL}}projects/ 
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###

POST {{baseURL}}projects/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{ "name": "Art Bash 2024" }

###

PATCH {{baseURL}}project/7/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{ "users": [8] }

###

DELETE {{baseURL}}project/7/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###





# *** CRUD capabilities for Task **********************************************
GET {{baseURL}}tasks/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###

POST {{baseURL}}tasks/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{
    "project": 9,
    "title": "Jump ball",
    "description": "Loreum Ipusm"
}

###


PATCH {{baseURL}}tasks/3/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{
    "title": "swimming",
    "description": "Loreum Ipusm Loreum Ipusm"
}

###


DELETE {{baseURL}}tasks/3/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###
