# Admin 1: 
# { "email": "jed@jed.com", "password": "MagicPassword1234!"}

# Staff 2:
# {"email": "clear@dave.com", "password": "CleanTables1234!"}


# Regular User 3:
# {"email": "johndoe@company.com", "password": "I Love Burgers!"}


###
@email = "clear@dave.com"
@password = "CleanTables1234!"
@authToken = {{login.response.headers.X-AuthToken}}
@CSRFToken = abcde
@baseURL = http://127.0.0.1:8000/

###

# *** LOGIN and LOGTOUT ***********************************************
POST {{baseURL}}login/ 
Content-Type: application/json

{"email": {{email}}, "password": {{password}}}

###

POST {{baseURL}}logout/ 
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###

# *** CRUD capabilities for Tenant ***********************************************
GET {{baseURL}}tenants/ 
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###

POST {{baseURL}}tenant/new/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{ "name": "boom.com" }

###

PUT {{baseURL}}tenant/5/ 
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{"name": "bob.com"}

###

DELETE {{baseURL}}tenant/delete/5/ 
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###


# *** CRUD capabilities for User ***********************************************
GET {{baseURL}}users/ 
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###

POST {{baseURL}}users/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{"name": "Max", "email": "max@dave.com", "password": "max"}

###

PUT {{baseURL}}user/2/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{"name": "Nor4man"}

###

DELETE  {{baseURL}}user/6/
Content-Type: application/json
Authorization: {{authToken}}
X-CSRFToken: {{CSRFToken}}

{}

###


# *** CRUD capabilities for Project ***********************************************
GET {{baseURL}}projects/ 
Content-Type: application/json

{}

###

POST {{baseURL}}projects/
Content-Type: application/json

{ "tenant": 2, "users": [2], "name": "Launch New Business" }

###

PATCH {{baseURL}}project/1/
Content-Type: application/json

{ "name": "Artwork" }

###

DELETE {{baseURL}}project/1/
Content-Type: application/json

{}

###

# *** CRUD capabilities for Task ***********************************************
GET {{baseURL}}tasks/
Content-Type: application/json

{}

###

POST {{baseURL}}tasks/
Content-Type: application/json

{
    "tenant": 2,
    "users": [2],
    "project": 2,
    "title": "Market research",
    "description": "Loreum Ipusm"
}

###


PATCH {{baseURL}}tasks/1/
Content-Type: application/json

{
    "title": "RACI matrix",
    "description": "Loreum Ipusm Loreum Ipusm"
}

###


DELETE {{baseURL}}tasks/1/
Content-Type: application/json

{}

###