# Generated by Django 5.1.2 on 2024-10-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='users',
        ),
    ]
